#' Plot model and data from \code{tidydrc()}
#'
#' A \code{ggplot} wrapper function for plotting the dose-response model fit and
#' the data from the list-column output of \code{tidydrc()}
#'
#' @author Angel Angelov
#'
#' @param modeldf A list-column dataframe, generated by \code{tidydrc()}
#' @param ed50 Logical, whether to draw a line indicating the ED50 (effective
#'   dose for half maximal response).
#' @param confint Logical, whether to draw confidence bands around the fitted
#'   regression curve as a \code{geom_ribbon}
#' @param ... Arguments passed on to \code{aes()} of ggplot, as in
#'   \code{ggplot(aes(...))}
#'
#' @usage tidydrc_plot(modeldf, ed50 = FALSE, confint = FALSE, ...)
#'
#' @examples
#' # directly piping the output of tidydrc()
#' library(tidyverse)
#' p <- tidydrc_model(S.alba, Dose, DryMatter, model = LL.4(), Herbicide) %>%
#'   tidydrc_plot(ed50 = TRUE, confint = TRUE, color = ~Herbicide)
#' p
#'
#' # the ggplot object can be manipulated further as usual
#' p + facet_wrap(~Herbicide, ncol = 1) +
#'   scale_x_log10() +
#'   labs(title = "Potency of glyphosate and bentazone in Sinapsis alba")
#' @export

tidydrc_plot <-
  function(modeldf,
           ed50 = FALSE,
           confint = FALSE,
           ...) {
    p <- modeldf %>%
      tidyr::unnest(data) %>%
      ggplot2::ggplot(ggplot2::aes_(...)) +
      ggplot2::geom_point(ggplot2::aes_(~d, ~r),
        alpha = 0.6,
        stroke = 0,
        size = 2
      ) +
      ggplot2::geom_line(
        ggplot2::aes_(~dose, ~pred),
        data = modeldf %>%
          tidyr::unnest(pred)
      ) +
      ggplot2::theme_bw() + 
      ggplot2::scale_x_log10()

    if (ed50) {
      p <- p + ggplot2::geom_vline(
        ggplot2::aes_(xintercept = ~`e:(Intercept)`, ...),
        linetype = 5,
        data = modeldf %>%
          tidyr::unnest(coefs) %>%
          tidyr::pivot_wider(
            values_from = value,
            names_from = parameter
          )
      )
    }

    if (confint) {
      p <- p +
        ggplot2::geom_ribbon(
          ggplot2::aes_(
            x = ~dose,
            ymin = ~Lower,
            ymax = ~Upper,
            ...
          ),
          alpha = 0.2,
          size = 0,
          data = modeldf %>%
            tidyr::unnest(pred)
        )
    }

    return(p)
  }
